defaults:
  - model: autoregressive_dino_foresight_latent
  - vae: raw/convnext_isotropic_large
  - training: dino_foresight_4x_accum_4x
  - transforms: dino_foresight
  - recipe: dino_foresight_variable_length
  - data: cityscapes
  - _self_
objective: CFM
name: autoregressive_dino_foresight_latent(${objective}, vae=${vae.name}, variable_length, longer)
experiment_path: /work/gabrijel/experiments/vgg-wm/cityscapes/224x448/${name}