name: dino_foresight
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.5=h4612cfd_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py313h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - autopep8==2.3.2
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - braceexpand==0.1.7
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cuda-bindings==12.9.2
      - cuda-pathfinder==1.1.0
      - cuda-python==12.9.2
      - cudf-cu12==25.8.0
      - cuml-cu12==25.8.0
      - cupy-cuda12x==13.6.0
      - cuvs-cu12==25.8.0
      - cycler==0.12.1
      - dask==2025.7.0
      - dask-cuda==25.8.0
      - dask-cudf-cu12==25.8.0
      - debugpy==1.8.16
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distlib==0.4.0
      - distributed==2025.7.0
      - distributed-ucxx-cu12==0.45.1
      - einops==0.8.1
      - executing==2.2.0
      - fastjsonschema==2.21.2
      - fastrlock==0.8.3
      - filelock==3.13.1
      - fonttools==4.59.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - h11==0.16.0
      - hf-xet==1.1.8
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - identify==2.6.14
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.2.2
      - libcudf-cu12==25.8.0
      - libcuml-cu12==25.8.0
      - libcuvs-cu12==25.8.0
      - libkvikio-cu12==25.8.0
      - libraft-cu12==25.8.0
      - librmm-cu12==25.8.0
      - libucx-cu12==1.18.1
      - libucxx-cu12==0.45.1
      - lightning-utilities==0.15.2
      - llvmlite==0.44.0
      - locket==1.0.0
      - lpips==0.1.4
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nodeenv==1.9.1
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numba-cuda==0.14.1
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cccl-cu12==12.9.27
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - nvtx==0.2.13
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parso==0.8.5
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.4.0
      - pre-commit==4.3.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycodestyle==2.14.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pylibcudf-cu12==25.8.0
      - pylibraft-cu12==25.8.0
      - pynvjitlink-cu12==0.7.0
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.2
      - raft-dask-cu12==25.8.0
      - rapids-dask-dependency==25.8.0
      - rapids-logger==0.1.1
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rmm-cu12==25.8.0
      - rpds-py==0.27.0
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.35.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.13.3
      - tblib==3.1.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch==2.8.0+cu126
      - torch-dct==0.1.6
      - torch-fidelity==0.3.0
      - torchdiffeq==0.2.5
      - torchinfo==1.8.0
      - torchmetrics==1.8.1
      - torchvision==0.23.0+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - treelite==4.4.1
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ucx-py-cu12==0.45.0
      - ucxx-cu12==0.45.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - virtualenv==20.34.0
      - wandb==0.21.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webdataset==1.0.2
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xformers==0.0.32.post2
      - yarl==1.20.1
      - zict==3.0.0
prefix: /athenahomes/gabrijel/miniconda3/envs/dino_foresight
