defaults:
  - model: raw/convnext_isotropic_base
  - training: ilsvrc
  - transforms: ilsvrc
  - data: ilsvrc
  - _self_

data:
  dataset_root: /lus/lfs1aip2/projects/u5dn/vgg-wm/datasets/ILSVRC_PREPROCESSED
  
model:
  intermediate_layers: [-1]
  input_dim: 768
  feature_stats: /home/u5dn/gabrijel.u5dn/code/vgg-wm-vae/feature_stats/ilsvrc/lowres/dino.npz
  latent_channels: 8

name: ${model.name}(${objective}, beta=${model.beta})
resolution: low
objective: AE
experiment_path: /lus/lfs1aip2/projects/u5dn/vgg-wm/experiments/vae/ilsvrc/resolution=${resolution}