defaults:
  - model: raw/dino_foresight_transformer_base_rgb_decoder
  - training: rgb/ilsvrc
  - transforms: ilsvrc
  - data: ilsvrc
  - _self_

data:
  dataset_root: /lus/lfs1aip2/projects/u5dn/vgg-wm/datasets/ILSVRC_PREPROCESSED
  
model:
  dino_intermediate_layers: [-1]
  input_dim: 768
  feature_stats: /home/u5dn/gabrijel.u5dn/code/vgg-wm-vae/feature_stats/ilsvrc/lowres/dino.npz

name: ${model.name}
resolution: low
experiment_path: /lus/lfs1aip2/projects/u5dn/vgg-wm/experiments/rgb/ilsvrc/resolution=${resolution}