dinov2_variant: "vitb14_reg"
feature_stats: "/users/gabrijel/projects/vgg-wm/stats/kubric/movi_a/dino_dist.npz"
intermediate_layers: [2, 5, 8, 11]
sequence_length: 5
img_size: [224, 224]
patch_size: 14
separable_attention: True
separable_window_size: 1

layers: 12
heads: 8
input_dim: 3072
hidden_dim: 1152
dropout: 0.1