# Experiment settings
wandb: true
seed: 123
epochs: 2400
steps: 362400

# Logging & checkpointing
log_every_steps: 16
ckpt_every_epochs: 50
sample_every_epochs: 50
evaluate_every_epochs: 25
effective_batch_size: 64
num_workers: 8

# Optimization
lr: 8e-5
clip_grad_norm: 1.0
accumulation_steps: 1
lr_scheduler:
  name: cosine

# Recipe
recipe: "dino_foresight"