# Experiment settings
wandb: true
seed: 123
epochs: 6400 # 151
steps: 966400

# Logging & checkpointing
log_every_steps: 16
ckpt_every_epochs: 400
sample_every_epochs: 100
evaluate_every_epochs: 100
effective_batch_size: 64
num_workers: 8

# Optimization
lr: 8e-5
clip_grad_norm: 1.0
accumulation_steps: 1
lr_scheduler:
  name: cosine

# Recipe
recipe: "dino_foresight"