name: "dino_foresight_vit_base_rgb_decoder"
dinov2_variant: "vitb14_reg"
dino_intermediate_layers: [2, 5, 8, 11]
decoder_intermediate_layers: [2, 5, 8, 11]
resolution: [224, 224]
patch_size: 14
num_layers: 12
heads: 12
input_dim: 3072
hidden_dim: 768
mlp_dim: 3072
dropout: 0.1
shape: [16, 16]
use_qk_norm: true
num_registers: 4

feature_stats: "/users/gabrijel/projects/vgg-wm-vae/feature_stats/kubric/movi_a/dino.npz"