name: "symmetric_vit_large"
dinov2_variant: "vitb14_reg"
feature_stats: "/users/gabrijel/projects/vgg-wm-vae/feature_stats/kubric/movi_a/dino.npz"
intermediate_layers: [2, 5, 8, 11]
patch_size: 14
num_encoder_layers: 24
num_decoder_layers: 24
heads: 16
input_dim: 3072
hidden_dim: 1024
mlp_dim: 4096
latent_channels: 16
dropout: 0.1
shape: [16, 16]
use_qk_norm: true
beta: 0
abs_pos_enc: true
num_registers: 0