name: "symmetric_vit_base"
dinov2_variant: "vitb14_reg"
feature_stats: "/users/gabrijel/projects/vgg-wm-vae/feature_stats/kubric/movi_a/dino.npz"
intermediate_layers: [2, 5, 8, 11]
patch_size: 14
num_encoder_layers: 12
num_decoder_layers: 12
heads: 12
input_dim: 3072
hidden_dim: 768
mlp_dim: 3072
latent_channels: 16
dropout: 0.1
shape: [16, 16]
use_qk_norm: true
beta: 0
abs_pos_enc: true