name: "dino_foresight_pca_symmetric_vit_base"
dinov2_variant: "vitb14_reg"
pca_ckpt: "/scratch/shared/beegfs/gabrijel/hf/dino-foresight/kubric/pca/subsample_ratio=0.33/dino_pca_224_l[2,_5,_8,_11]_1152.pth"
pca_stats: "/scratch/shared/beegfs/gabrijel/hf/dino-foresight/kubric/pca/subsample_ratio=0.33/pca_dist_stats.npz"
intermediate_layers: [2, 5, 8, 11]
img_size: [224, 224]
patch_size: 14
num_encoder_layers: 12
num_decoder_layers: 12
heads: 12
input_dim: 1152
hidden_dim: 768
mlp_dim: 3072
latent_channels: 16
dropout: 0.1
shape: [16, 16]
use_qk_norm: true
beta: 0