# Experiment settings
wandb: true
seed: 42
epochs: 400 # num steps per epoch 3082 => 
steps: 1232800

# Logging & checkpointing
log_every_steps: 8
ckpt_every_epochs: 1
sample_every_epochs: 25
evaluate_every_epochs: 1
effective_batch_size: 256
validation_batch_size: 16
num_workers: 16

# Optimization
lr: 3e-4
clip_grad_norm: 1.0
accumulation_steps: 4
lr_scheduler:
  name: linear_warmup
  warmup_steps: 3700

mixed_precision: true