
objective: VAE
name: ${vae.model.name}(${vae.objective}, beta=${vae.model.beta})

model:
  name: "raw_convnext_isotropic_base"
  dinov2_variant: "vitb14_reg"
  feature_stats: "/athenahomes/gabrijel/projects/vgg-wm-vae/feature_stats/cityscapes/lowres/dino.npz"
  intermediate_layers: [2, 5, 8, 11]
  patch_size: 14
  input_dim: 3072
  depth: 18
  dim: 768
  latent_channels: 16
  drop_path_rate: 0
  layer_scale_init_value: 0
  shape: [16, 32]
  beta: 0.01

ckpt_path: /scratch/shared/beegfs/gabrijel/experiments/vgg-wm-vae/cityscapes/resolution=low/${vae.name}/${vae.name}/checkpoints/best.pt
latent_dist_stats_path: /athenahomes/gabrijel/projects/vgg-wm-vae/feature_stats/cityscapes/lowres/${vae.name}.npz