# Experiment settings
wandb: true
seed: 42
epochs: 400 # num steps per epoch 697 => 
steps: 278800

# Logging & checkpointing
log_every_steps: 8
ckpt_every_epochs: 10
sample_every_epochs: 10
evaluate_every_epochs: 10
effective_batch_size: 256
validation_batch_size: 16
num_workers: 16

# Optimization
lr: 4e-5
clip_grad_norm: 1.0
accumulation_steps: 2
lr_scheduler:
  name: linear_warmup
  warmup_steps: 13940

mixed_precision: true