# Experiment settings
wandb: true
seed: 42
epochs: 100 # num steps per epoch 2502 => 
steps: 250200

# Logging & checkpointing
log_every_steps: 8
ckpt_every_epochs: 5
sample_every_epochs: 1
evaluate_every_epochs: 1
effective_batch_size: 512
validation_batch_size: 32
num_workers: 16

# Optimization
lr: 4e-5
clip_grad_norm: 1.0
accumulation_steps: 1
lr_scheduler:
  name: linear_warmup
  warmup_steps: 12510 # 5%

mixed_precision: true