defaults:
  - model: autoregressive_dino_foresight_pca_ncomponents=16_with_normalization
  - training: dino_foresight_3x
  - transforms: dino_foresight
  - data: movi_a
  - recipe: dino_foresight_variable_length
  - _self_
objective: CFM
name: autoregressive_dino_foresight_pca(${objective}, ncomponents=16, 3x, variable_length)
experiment_path: /scratch/shared/beegfs/gabrijel/experiments/vgg-wm/kubric/${name}