defaults:
  - model: autoregressive_dino_foresight_pca_with_normalization
  - training: dino_foresight_3x_linear_warmup
  - transforms: dino_foresight
  - recipe: dino_foresight
  - data: movi_a
  - _self_
objective: CFM
name: autoregressive_dino_foresight_pca(${objective}, 3x, normalization, linear)
experiment_path: /scratch/shared/beegfs/gabrijel/experiments/vgg-wm/autoregressive_dino_foresight_pca