defaults:
  - model: autoregressive_dino_foresight_latent
  - vae: raw/convnext_isotropic_base
  - training: dino_foresight_3x
  - transforms: dino_foresight
  - recipe: dino_foresight_variable_length
  - data: movi_a
  - _self_
objective: CFM
name: autoregressive_dino_foresight_latent(${objective}, vae=${vae.name}, variable_length)
experiment_path: /scratch/shared/beegfs/gabrijel/experiments/vgg-wm/${name}